# Generated by Django 6.0 on 2026-01-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('completed', 'completed')], max_length=15),
        ),
    ]
